<?php

/**
 * @file
 * Provides hooks and functionality for the Elastic APM module.
 */

/**
 * Implements hook_page_attachments.
 *
 * Adds the javascript file required for Real User Monitoring. Currently
 * included in all pages; that will change once including/excluding pages from
 * monitoring is implemented.
 */
function elastic_apm_page_attachments(array &$page) {
  if (!(\Drupal::service('elastic_apm.api_service')->isRumAgentEnabled())) {
    return;
  }

  $page['#attached']['library'][] = 'elastic_apm/rum';
}

